name: Test dotnet app
on: push
jobs:
  test_my_code:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore
      - name: Test App
        run: dotnet test