name: Test dotnet app
on: 
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: 
      - self-hosted
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Test with dotnet
        run: dotnet test
      - name: Build App
        run: dotnet publish -c Release -r win-x64 -o publish

    
  
